// <auto-generated />
using System;
using CleanArchitecture.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CleanArchitecture.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(CleanArchitectureDbContext))]
    [Migration("20181128221120_initial2")]
    partial class initial2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CleanArchitecture.Core.Entities.BaseEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedTime")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<DateTime>("ModifiedTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.ToTable("BaseEntity");

                    b.HasDiscriminator<string>("Discriminator").HasValue("BaseEntity");
                });

            modelBuilder.Entity("CleanArchitecture.Core.Entities.ShoppingItem", b =>
                {
                    b.HasBaseType("CleanArchitecture.Core.Entities.BaseEntity");

                    b.Property<Guid>("Guid");

                    b.Property<string>("Name");

                    b.Property<double>("Quantity");

                    b.Property<long?>("ShoppingListId");

                    b.Property<int>("Type");

                    b.HasIndex("ShoppingListId");

                    b.ToTable("ShoppingItem");

                    b.HasDiscriminator().HasValue("ShoppingItem");
                });

            modelBuilder.Entity("CleanArchitecture.Core.Entities.ShoppingList", b =>
                {
                    b.HasBaseType("CleanArchitecture.Core.Entities.BaseEntity");

                    b.Property<Guid>("Guid")
                        .HasColumnName("ShoppingList_Guid");

                    b.Property<string>("Name")
                        .HasColumnName("ShoppingList_Name");

                    b.ToTable("ShoppingList");

                    b.HasDiscriminator().HasValue("ShoppingList");
                });

            modelBuilder.Entity("CleanArchitecture.Core.Entities.ShoppingItem", b =>
                {
                    b.HasOne("CleanArchitecture.Core.Entities.ShoppingList")
                        .WithMany("Items")
                        .HasForeignKey("ShoppingListId");
                });
#pragma warning restore 612, 618
        }
    }
}
